FROM --platform=linux/amd64 continuumio/miniconda3:24.7.1-0

WORKDIR /opt/adme

COPY server ./

RUN conda env create -f environment.yml

ENV PATH=/opt/conda/envs/ncats-adme/bin:$PATH

EXPOSE 5000

CMD ["python", "app.py"]

