FROM node:20 AS build

WORKDIR /opt/adme

COPY client ./

RUN npm install && npm install -g @angular/cli

# parameter for adme.ncats subdomain
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN ng build --configuration production --deploy-url=/models/client/ --base-href=/models

FROM --platform=linux/amd64 continuumio/miniconda3:24.7.1-0

# Install required packages
RUN apt-get update && apt-get install -y iproute2 && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/adme

COPY server ./

RUN conda env create -f environment.yml

ENV PATH /opt/conda/envs/ncats-adme/bin:$PATH

RUN chmod +x startup.sh

# clean existing client folder
RUN rm -rf client
COPY --from=build /opt/adme/dist/client client

CMD /bin/bash startup.sh

EXPOSE 5000

